"""add phase 2 persistence

Revision ID: 20260912_0001
Revises: 20260912_0000
Create Date: 2026-09-12 21:56:21.131623
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from app.persistence import types as persistence_types


revision: str = '20260912_0001'
down_revision: Union[str, None] = '20260912_0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('canonical_address', sa.String(length=160), nullable=False),
    sa.Column('display_address', sa.String(length=160), nullable=False),
    sa.Column('address_type', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('last_seen_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'canonical_address', name='uq_address_chain_canonical')
    )
    op.create_table('agencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('contract_address', sa.String(length=160), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.CheckConstraint('decimals >= 0 AND decimals <= 36', name='ck_asset_decimals'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'symbol', 'contract_address', name='uq_asset_identity')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('byte_length', sa.String(length=40), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('retention_until', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('graph_projection_checkpoints',
    sa.Column('projection_name', sa.String(length=100), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('source_digest', sa.String(length=64), nullable=False),
    sa.Column('projected_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('projection_name')
    )
    op.create_table('ml_dataset_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('period_start', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('period_end', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('retention_policy', sa.String(length=80), nullable=False),
    sa.Column('access_scope', sa.JSON(), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_hash'),
    sa.UniqueConstraint('version')
    )
    op.create_table('ml_feature_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('units', sa.String(length=40), nullable=True),
    sa.Column('window_definition', sa.JSON(), nullable=False),
    sa.Column('cutoff_policy', sa.JSON(), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_hash'),
    sa.UniqueConstraint('name', 'version', name='uq_feature_definition')
    )
    op.create_table('ml_feature_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=80), nullable=False),
    sa.Column('temporal_partition', sa.String(length=24), nullable=False),
    sa.Column('event_cutoff', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('availability_cutoff', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('max_event_time', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('max_available_time', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_hash')
    )
    op.create_table('ml_label_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('observation_window_start', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('observation_window_end', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('label', sa.String(length=24), nullable=False),
    sa.Column('maturity', sa.String(length=24), nullable=False),
    sa.Column('known_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('evidence_snapshot_ids', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_id', 'revision', name='uq_label_revision')
    )
    op.create_table('networks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('finality_policy', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('deduplication_key', sa.String(length=180), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('occurred_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('published_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deduplication_key')
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index('ix_outbox_dispatch', ['state', 'next_attempt_at', 'occurred_at'], unique=False)

    op.create_table('protocol_contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('protocol_name', sa.String(length=120), nullable=False),
    sa.Column('protocol_version', sa.String(length=60), nullable=True),
    sa.Column('protocol_type', sa.String(length=40), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('contract_address', sa.String(length=160), nullable=False),
    sa.Column('valid_from', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('valid_to', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('reviewed_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'contract_address', 'protocol_version', name='uq_protocol_contract')
    )
    op.create_table('provider_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('event_time', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('published_time', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('available_time', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('fetched_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('ingested_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('coverage_state', sa.String(length=24), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('cursor', sa.String(length=300), nullable=True),
    sa.Column('parser_version', sa.String(length=80), nullable=False),
    sa.Column('response_digest', sa.String(length=64), nullable=False),
    sa.Column('block_height', sa.String(length=78), nullable=True),
    sa.Column('block_hash', sa.String(length=150), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=True),
    sa.Column('finality_state', sa.String(length=24), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'chain', 'request_fingerprint', 'response_digest', name='uq_provider_observation')
    )
    op.create_table('api_clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('credential_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('expires_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('revoked_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_clients_agency_id'), ['agency_id'], unique=False)

    op.create_table('entity_address_assertions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('address_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('confidence', persistence_types.ExactDecimal(length=100), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('evidence_uri', sa.Text(), nullable=True),
    sa.Column('valid_from', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('valid_to', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('recorded_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('assertion_digest', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assertion_digest')
    )
    op.create_table('ml_dataset_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=150), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('license_name', sa.String(length=150), nullable=False),
    sa.Column('acquired_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_snapshot_id'], ['ml_dataset_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_label_adjudications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label_revision_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('adjudicated_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['label_revision_id'], ['ml_label_revisions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_split_manifests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('temporal_rules', sa.JSON(), nullable=False),
    sa.Column('group_rules', sa.JSON(), nullable=False),
    sa.Column('purge_duration', sa.String(length=40), nullable=False),
    sa.Column('embargo_duration', sa.String(length=40), nullable=False),
    sa.Column('membership_uri', sa.Text(), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_snapshot_id'], ['ml_dataset_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manifest_hash'),
    sa.UniqueConstraint('version')
    )
    op.create_table('normalized_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('tx_hash', sa.String(length=180), nullable=False),
    sa.Column('transfer_index', sa.String(length=80), nullable=False),
    sa.Column('from_address_id', sa.String(length=36), nullable=False),
    sa.Column('to_address_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('amount', persistence_types.ExactDecimal(length=100), nullable=False),
    sa.Column('raw_amount', sa.String(length=100), nullable=False),
    sa.Column('fiat_value', persistence_types.ExactDecimal(length=100), nullable=True),
    sa.Column('fiat_currency', sa.String(length=8), nullable=True),
    sa.Column('valuation_source', sa.String(length=64), nullable=True),
    sa.Column('valuation_time', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('event_time', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('available_time', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('ingested_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('provider_observation_id', sa.String(length=36), nullable=False),
    sa.Column('block_height', sa.String(length=78), nullable=True),
    sa.Column('block_hash', sa.String(length=180), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=True),
    sa.Column('finality_state', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_address_id'], ['address_records.id'], ),
    sa.ForeignKeyConstraint(['provider_observation_id'], ['provider_observations.id'], ),
    sa.ForeignKeyConstraint(['to_address_id'], ['address_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain', 'tx_hash', 'transfer_index', name='uq_normalized_transfer')
    )
    with op.batch_alter_table('normalized_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_normalized_tx_addresses', ['from_address_id', 'to_address_id'], unique=False)
        batch_op.create_index('ix_normalized_tx_event_time', ['chain', 'event_time'], unique=False)

    op.create_table('policy_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('effective_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('policy_name', 'version', name='uq_policy_version')
    )
    op.create_table('user_agency_scopes',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('valid_from', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('valid_to', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'agency_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('issued_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('expires_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('revoked_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('last_seen_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('victims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('name_ciphertext', sa.Text(), nullable=True),
    sa.Column('phone_ciphertext', sa.Text(), nullable=True),
    sa.Column('email_ciphertext', sa.Text(), nullable=True),
    sa.Column('pii_key_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('victims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_victims_agency_id'), ['agency_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('previous_digest', sa.String(length=64), nullable=True),
    sa.Column('event_digest', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_digest'),
    sa.UniqueConstraint('sequence')
    )
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('lock_expires_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('updated_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.CheckConstraint('attempt >= 0 AND max_attempts > 0', name='ck_job_attempts'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation', 'idempotency_key', name='uq_job_operation_idempotency')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_jobs_claim', ['state', 'next_attempt_at', 'priority'], unique=False)

    op.create_table('case_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'sequence', name='uq_case_event_sequence')
    )
    with op.batch_alter_table('case_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_events_case_id'), ['case_id'], unique=False)

    op.create_table('case_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body_ciphertext', sa.Text(), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['case_notes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_case_note_revision')
    )
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_notes_case_id'), ['case_id'], unique=False)

    op.create_table('complaint_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agency_id', sa.String(length=36), nullable=False),
    sa.Column('victim_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_reference', sa.String(length=150), nullable=False),
    sa.Column('narrative_ciphertext', sa.Text(), nullable=True),
    sa.Column('reported_loss', persistence_types.ExactDecimal(length=100), nullable=False),
    sa.Column('loss_currency', sa.String(length=12), nullable=False),
    sa.Column('incident_time', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('filed_time', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('received_time', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'source', 'external_reference', name='uq_complaint_external')
    )
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_records_agency_id'), ['agency_id'], unique=False)

    op.create_table('cross_chain_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('protocol_contract_id', sa.String(length=36), nullable=False),
    sa.Column('message_identity', sa.String(length=180), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=36), nullable=False),
    sa.Column('destination_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('evidence_snapshot_ids', sa.JSON(), nullable=False),
    sa.Column('observed_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['destination_transaction_id'], ['normalized_transactions.id'], ),
    sa.ForeignKeyConstraint(['protocol_contract_id'], ['protocol_contracts.id'], ),
    sa.ForeignKeyConstraint(['source_transaction_id'], ['normalized_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_contract_id', 'message_identity', name='uq_cross_chain_message')
    )
    op.create_table('evidence_manifests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('object_ids', sa.JSON(), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_evidence_manifest_revision'),
    sa.UniqueConstraint('manifest_hash')
    )
    with op.batch_alter_table('evidence_manifests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_manifests_case_id'), ['case_id'], unique=False)

    op.create_table('evidence_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=40), nullable=False),
    sa.Column('event_time', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('available_time', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('ingested_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('temporal_class', sa.String(length=24), nullable=False),
    sa.CheckConstraint("temporal_class IN ('pre_report','at_report','post_report')", name='ck_evidence_temporal_class'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_evidence_snapshot_revision')
    )
    with op.batch_alter_table('evidence_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_snapshots_case_id'), ['case_id'], unique=False)

    op.create_table('ml_experiment_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_run_id', sa.String(length=150), nullable=False),
    sa.Column('dataset_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('split_manifest_id', sa.String(length=36), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=80), nullable=False),
    sa.Column('seeds', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('environment', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifact_manifest', sa.JSON(), nullable=False),
    sa.Column('started_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('completed_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.ForeignKeyConstraint(['dataset_snapshot_id'], ['ml_dataset_snapshots.id'], ),
    sa.ForeignKeyConstraint(['split_manifest_id'], ['ml_split_manifests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_run_id')
    )
    op.create_table('monitoring_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('address_id', sa.String(length=36), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('expires_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('policy_version', sa.String(length=80), nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address_records.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_subscriptions_case_id'), ['case_id'], unique=False)

    op.create_table('report_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('report_timestamp', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('reported_timezone', sa.String(length=64), nullable=False),
    sa.Column('timestamp_precision', sa.String(length=24), nullable=False),
    sa.Column('verification_state', sa.String(length=24), nullable=False),
    sa.Column('verified_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('external_event_id', sa.String(length=150), nullable=True),
    sa.Column('received_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['report_events.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_report_event_case_revision'),
    sa.UniqueConstraint('source_system', 'external_event_id', name='uq_report_event_source_external')
    )
    with op.batch_alter_table('report_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_events_case_id'), ['case_id'], unique=False)

    op.create_table('alert_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('delivered_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_deliveries_alert_id'), ['alert_id'], unique=False)

    op.create_table('alert_recipients',
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('read_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('acknowledged_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'user_id')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('run_type', sa.String(length=40), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('report_event_id', sa.String(length=36), nullable=False),
    sa.Column('root_address_ids', sa.JSON(), nullable=False),
    sa.Column('event_cutoff', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('cutoff_available_time', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=False),
    sa.Column('requested_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('started_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('completed_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_event_id'], ['report_events.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'run_type', 'revision', name='uq_analysis_run_revision')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_case_id'), ['case_id'], unique=False)

    op.create_table('bitcoin_outpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('output_index', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.String(length=36), nullable=True),
    sa.Column('amount_satoshi', sa.String(length=100), nullable=False),
    sa.Column('spent_by_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_snapshot_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address_records.id'], ),
    sa.ForeignKeyConstraint(['evidence_snapshot_id'], ['evidence_snapshots.id'], ),
    sa.ForeignKeyConstraint(['spent_by_transaction_id'], ['normalized_transactions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['normalized_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'output_index', name='uq_bitcoin_outpoint')
    )
    with op.batch_alter_table('bitcoin_outpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bitcoin_outpoints_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('case_complaints',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('linked_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('linked_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('case_id', 'complaint_id')
    )
    op.create_table('clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('evidence_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('source_method', sa.String(length=100), nullable=False),
    sa.Column('confidence', persistence_types.ExactDecimal(length=100), nullable=False),
    sa.Column('available_time', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['evidence_snapshot_id'], ['evidence_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_digest')
    )
    op.create_table('complaint_wallets',
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('address_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('confidence', persistence_types.ExactDecimal(length=100), nullable=True),
    sa.Column('recorded_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id', 'address_id')
    )
    op.create_table('ml_model_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('experiment_run_id', sa.String(length=36), nullable=False),
    sa.Column('model_hash', sa.String(length=64), nullable=False),
    sa.Column('preprocessing_version', sa.String(length=80), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=80), nullable=False),
    sa.Column('calibrator_version', sa.String(length=80), nullable=False),
    sa.Column('calibrator_hash', sa.String(length=64), nullable=False),
    sa.Column('target_definition', sa.JSON(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['experiment_run_id'], ['ml_experiment_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('analysis_run_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('occurred_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='ck_analysis_progress'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_analysis_event_sequence')
    )
    with op.batch_alter_table('analysis_run_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_run_events_run_id'), ['run_id'], unique=False)

    op.create_table('cluster_memberships',
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('address_id', sa.String(length=36), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', persistence_types.ExactDecimal(length=100), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', 'address_id')
    )
    op.create_table('graph_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('report_event_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('cutoff_available_time', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('selected_filters', sa.JSON(), nullable=False),
    sa.Column('membership_digest', sa.String(length=64), nullable=False),
    sa.Column('projection_revision', sa.Integer(), nullable=False),
    sa.Column('continuity_gaps', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_event_id'], ['report_events.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_graph_snapshot_revision')
    )
    with op.batch_alter_table('graph_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_snapshots_case_id'), ['case_id'], unique=False)

    op.create_table('ml_drift_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_package_id', sa.String(length=36), nullable=False),
    sa.Column('cohort', sa.JSON(), nullable=False),
    sa.Column('window_start', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('window_end', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('metric_value', persistence_types.ExactDecimal(length=100), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('threshold', persistence_types.ExactDecimal(length=100), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['model_package_id'], ['ml_model_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('calibrator_version', sa.String(length=100), nullable=False),
    sa.Column('feature_snapshot_id', sa.String(length=100), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('calibrated_confidence', persistence_types.ExactDecimal(length=100), nullable=False),
    sa.Column('positive_class_probability', persistence_types.ExactDecimal(length=100), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('abstention_reason', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('event_cutoff', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('availability_cutoff', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('contributing_features', sa.JSON(), nullable=False),
    sa.Column('evidence_snapshot_ids', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('predicted_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_ml_risk_score'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_ml_prediction_revision')
    )
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_predictions_case_id'), ['case_id'], unique=False)

    op.create_table('risk_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('rule_version', sa.String(length=64), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('evidence_snapshot_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_risk_score'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_risk_result_revision')
    )
    with op.batch_alter_table('risk_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_results_case_id'), ['case_id'], unique=False)

    op.create_table('rule_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('policy_version', sa.String(length=80), nullable=False),
    sa.Column('temporal_partition', sa.String(length=24), nullable=False),
    sa.Column('measured_values', sa.JSON(), nullable=False),
    sa.Column('contribution', sa.Integer(), nullable=False),
    sa.Column('assessment_state', sa.String(length=24), nullable=False),
    sa.Column('evidence_snapshot_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'rule_id', 'policy_version', 'temporal_partition', name='uq_rule_finding')
    )
    with op.batch_alter_table('rule_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_findings_run_id'), ['run_id'], unique=False)

    op.create_table('trace_paths',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('path_index', sa.Integer(), nullable=False),
    sa.Column('hop_count', sa.Integer(), nullable=False),
    sa.Column('terminal_entity_id', sa.String(length=36), nullable=True),
    sa.Column('total_amount', persistence_types.ExactDecimal(length=100), nullable=True),
    sa.Column('path_payload', sa.JSON(), nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terminal_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'path_index', name='uq_trace_path_index')
    )
    with op.batch_alter_table('trace_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trace_paths_run_id'), ['run_id'], unique=False)

    op.create_table('alert_triggers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('prediction_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_snapshot_ids', sa.JSON(), nullable=False),
    sa.Column('triggered_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['ml_predictions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_table('analyst_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('disposition', sa.String(length=32), nullable=False),
    sa.Column('override_score', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reviewed_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('review_expires_at', persistence_types.UtcTimestamp(length=35), nullable=True),
    sa.Column('adjudication_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['adjudication_id'], ['ml_label_adjudications.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['ml_predictions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision', name='uq_analyst_review_revision')
    )
    with op.batch_alter_table('analyst_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_reviews_case_id'), ['case_id'], unique=False)

    op.create_table('deposit_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=100), nullable=False),
    sa.Column('idempotency_reference', sa.String(length=180), nullable=False),
    sa.Column('address_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=True),
    sa.Column('recommendation', sa.String(length=24), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('assessed_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('expires_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('evidence_summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address_records.id'], ),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['ml_predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'idempotency_reference', name='uq_deposit_decision')
    )
    op.create_table('ml_prediction_explanations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.String(length=36), nullable=False),
    sa.Column('feature_name', sa.String(length=120), nullable=False),
    sa.Column('measured_value', sa.JSON(), nullable=False),
    sa.Column('contribution', persistence_types.ExactDecimal(length=100), nullable=False),
    sa.Column('contribution_space', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('temporal_partition', sa.String(length=24), nullable=False),
    sa.Column('evidence_snapshot_ids', sa.JSON(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['ml_predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id', 'rank', name='uq_prediction_explanation_rank')
    )
    with op.batch_alter_table('ml_prediction_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_prediction_explanations_prediction_id'), ['prediction_id'], unique=False)

    op.create_table('ml_retraining_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drift_evaluation_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('updated_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['drift_evaluation_id'], ['ml_drift_evaluations.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('graph_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('risk_result_id', sa.String(length=36), nullable=True),
    sa.Column('ml_prediction_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_manifest', sa.JSON(), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('pdf_digest', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('report_cutoff', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.Column('review_status', sa.String(length=24), nullable=False),
    sa.Column('dispatch_status', sa.String(length=24), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', persistence_types.UtcTimestamp(length=35), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['graph_snapshot_id'], ['graph_snapshots.id'], ),
    sa.ForeignKeyConstraint(['ml_prediction_id'], ['ml_predictions.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['forensic_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_result_id'], ['risk_results.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['report_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'revision', name='uq_report_revision')
    )
    with op.batch_alter_table('report_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_revisions_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_revisions_report_id'))

    op.drop_table('report_revisions')
    op.drop_table('ml_retraining_requests')
    with op.batch_alter_table('ml_prediction_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_prediction_explanations_prediction_id'))

    op.drop_table('ml_prediction_explanations')
    op.drop_table('deposit_decisions')
    with op.batch_alter_table('analyst_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_reviews_case_id'))

    op.drop_table('analyst_reviews')
    op.drop_table('alert_triggers')
    with op.batch_alter_table('trace_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trace_paths_run_id'))

    op.drop_table('trace_paths')
    with op.batch_alter_table('rule_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_findings_run_id'))

    op.drop_table('rule_findings')
    with op.batch_alter_table('risk_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_results_case_id'))

    op.drop_table('risk_results')
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_predictions_case_id'))

    op.drop_table('ml_predictions')
    op.drop_table('ml_drift_evaluations')
    with op.batch_alter_table('graph_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_snapshots_case_id'))

    op.drop_table('graph_snapshots')
    op.drop_table('cluster_memberships')
    with op.batch_alter_table('analysis_run_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_run_events_run_id'))

    op.drop_table('analysis_run_events')
    op.drop_table('ml_model_packages')
    op.drop_table('complaint_wallets')
    op.drop_table('clusters')
    op.drop_table('case_complaints')
    with op.batch_alter_table('bitcoin_outpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bitcoin_outpoints_transaction_id'))

    op.drop_table('bitcoin_outpoints')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_case_id'))

    op.drop_table('analysis_runs')
    op.drop_table('alert_recipients')
    with op.batch_alter_table('alert_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_deliveries_alert_id'))

    op.drop_table('alert_deliveries')
    with op.batch_alter_table('report_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_events_case_id'))

    op.drop_table('report_events')
    with op.batch_alter_table('monitoring_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_subscriptions_case_id'))

    op.drop_table('monitoring_subscriptions')
    op.drop_table('ml_experiment_runs')
    with op.batch_alter_table('evidence_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_snapshots_case_id'))

    op.drop_table('evidence_snapshots')
    with op.batch_alter_table('evidence_manifests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_manifests_case_id'))

    op.drop_table('evidence_manifests')
    op.drop_table('cross_chain_links')
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_records_agency_id'))

    op.drop_table('complaint_records')
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_notes_case_id'))

    op.drop_table('case_notes')
    with op.batch_alter_table('case_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_events_case_id'))

    op.drop_table('case_events')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_claim')
        batch_op.drop_index(batch_op.f('ix_background_jobs_case_id'))

    op.drop_table('background_jobs')
    op.drop_table('audit_events')
    with op.batch_alter_table('victims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_victims_agency_id'))

    op.drop_table('victims')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    op.drop_table('user_agency_scopes')
    op.drop_table('policy_settings')
    with op.batch_alter_table('normalized_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_normalized_tx_event_time')
        batch_op.drop_index('ix_normalized_tx_addresses')

    op.drop_table('normalized_transactions')
    op.drop_table('ml_split_manifests')
    op.drop_table('ml_label_adjudications')
    op.drop_table('ml_dataset_sources')
    op.drop_table('entity_address_assertions')
    with op.batch_alter_table('api_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_clients_agency_id'))

    op.drop_table('api_clients')
    op.drop_table('provider_observations')
    op.drop_table('protocol_contracts')
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_dispatch')

    op.drop_table('outbox_events')
    op.drop_table('networks')
    op.drop_table('ml_label_revisions')
    op.drop_table('ml_feature_snapshots')
    op.drop_table('ml_feature_definitions')
    op.drop_table('ml_dataset_snapshots')
    op.drop_table('graph_projection_checkpoints')
    op.drop_table('evidence_objects')
    op.drop_table('entities')
    op.drop_table('assets')
    op.drop_table('agencies')
    op.drop_table('address_records')
    # ### end Alembic commands ###
