"""baseline legacy schema

Revision ID: 20260912_0000
Revises: none
Create Date: 2026-09-12 21:50:13.629011
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '20260912_0000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixer_bridge_directory',
    sa.Column('contract_address', sa.String(length=120), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('protocol_name', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('source_chain', sa.String(length=20), nullable=True),
    sa.Column('destination_chain', sa.String(length=20), nullable=True),
    sa.Column('risk_weight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('contract_address', 'chain')
    )
    op.create_table('transactions',
    sa.Column('tx_hash', sa.String(length=150), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('from_address', sa.String(length=120), nullable=False),
    sa.Column('to_address', sa.String(length=120), nullable=False),
    sa.Column('token_symbol', sa.String(length=20), nullable=True),
    sa.Column('token_contract', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_peeling_tx', sa.Boolean(), nullable=True),
    sa.Column('is_bridge_tx', sa.Boolean(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tx_hash')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('police_station', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vasp_directory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vasp_name', sa.String(length=150), nullable=False),
    sa.Column('legal_entity_name', sa.String(length=200), nullable=True),
    sa.Column('is_fiu_ind_registered', sa.Boolean(), nullable=True),
    sa.Column('fiu_registration_number', sa.String(length=100), nullable=True),
    sa.Column('nodal_officer_name', sa.String(length=150), nullable=True),
    sa.Column('nodal_officer_email', sa.String(length=255), nullable=False),
    sa.Column('law_enforcement_portal_url', sa.String(length=255), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('sla_freeze_hours', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_trail',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_entity', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('complaint_source', sa.String(length=30), nullable=True),
    sa.Column('external_complaint_id', sa.String(length=100), nullable=False),
    sa.Column('victim_name', sa.String(length=150), nullable=True),
    sa.Column('victim_phone', sa.String(length=30), nullable=True),
    sa.Column('reported_loss_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('loss_currency', sa.String(length=10), nullable=True),
    sa.Column('incident_timestamp', sa.DateTime(), nullable=True),
    sa.Column('complaint_text', sa.Text(), nullable=True),
    sa.Column('fraud_typology', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_tier', sa.String(length=20), nullable=True),
    sa.Column('possible_syndicate', sa.Boolean(), nullable=True),
    sa.Column('assigned_officer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_complaint_id')
    )
    op.create_table('vasp_addresses',
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('vasp_id', sa.String(length=36), nullable=False),
    sa.Column('address_tag', sa.String(length=100), nullable=False),
    sa.Column('source_provenance', sa.String(length=150), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vasp_id'], ['vasp_directory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address', 'chain')
    )
    op.create_table('wallets',
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('node_type', sa.String(length=30), nullable=True),
    sa.Column('vasp_id', sa.String(length=36), nullable=True),
    sa.Column('attribution_tier', sa.String(length=30), nullable=True),
    sa.Column('attribution_confidence', sa.Float(), nullable=True),
    sa.Column('attribution_evidence', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('total_received_usd', sa.Float(), nullable=True),
    sa.Column('risk_flags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vasp_id'], ['vasp_directory.id'], ),
    sa.PrimaryKeyConstraint('address', 'chain')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_wallets',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('wallet_address', sa.String(length=120), nullable=False),
    sa.Column('wallet_chain', sa.String(length=20), nullable=False),
    sa.Column('hop_depth', sa.Integer(), nullable=True),
    sa.Column('is_origin_reported', sa.Boolean(), nullable=True),
    sa.Column('is_terminal_destination', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'wallet_address', 'wallet_chain')
    )
    op.create_table('forensic_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('report_reference_number', sa.String(length=100), nullable=False),
    sa.Column('sha256_content_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_storage_path', sa.Text(), nullable=False),
    sa.Column('is_court_certified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_reference_number')
    )
    op.create_table('legal_notices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('vasp_id', sa.String(length=36), nullable=True),
    sa.Column('notice_type', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=False),
    sa.Column('target_wallet', sa.String(length=120), nullable=False),
    sa.Column('target_tx_hash', sa.String(length=150), nullable=True),
    sa.Column('amount_to_freeze', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('pdf_storage_path', sa.Text(), nullable=True),
    sa.Column('dispatched_to_email', sa.String(length=255), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vasp_id'], ['vasp_directory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legal_notices')
    op.drop_table('forensic_reports')
    op.drop_table('case_wallets')
    op.drop_table('alerts')
    op.drop_table('wallets')
    op.drop_table('vasp_addresses')
    op.drop_table('cases')
    op.drop_table('audit_trail')
    op.drop_table('vasp_directory')
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('mixer_bridge_directory')
    # ### end Alembic commands ###
